name: Notion Task Automation

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  automate-tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv notion-client

      - name: Run Notion task automation
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          TASK_CATEGORY_DB_ID: ${{ secrets.TASK_CATEGORY_DB_ID }}
          TODAYS_TASKS_DB_ID: ${{ secrets.TODAYS_TASKS_DB_ID }}
        run: python main.py
